### ISSUE TITLE
Ingest should not auto-approve submissions that weren't submitted by "insdc_ingest_user"

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#3087] opened 2024-10-28 12:40 UTC
Relevant for curation of insdc data: https://loculus.slack.com/archives/C05G172HL6L/p1730118798464579?thread_ts=1730118697.621189&cid=C05G172HL6L

**Comment by chaoran-chen** [comment] 2024-10-30 22:40
Duplicate of #2613 ;) I'll close the old one as this one is more actively used and linked from the current PR.

**Closed** 2024-10-31 12:31 UTC
Labels: ingest
