### ISSUE TITLE
File downloads should include date of download

### ISSUE THREAD

**Issue by anna-parker** [loculus-project/loculus#2689] opened 2024-09-02 09:53 UTC

**Comment by theosanderson** [comment] 2024-09-02 22:33
Dupe of: https://github.com/loculus-project/loculus/issues/2327 but useful to have this nearer the top!

**Comment by corneliusroemer** [comment] 2024-09-03 09:18
@anna-parker just a quick follow up - how would you include the date of download? Your initial issue doesn't provide any suggested implementation. Is the file name sufficient? In TSV it's not so easy to embed extra metadata. In JSON we could easily add all sorts of download related metadata.

**Closed** 2024-10-21 13:47 UTC
Labels: website, feature, silo/LAPIS
