### ISSUE TITLE
E2E errors sometimes with: `Error: page.goto: Connection terminated unexpectedly`

### ISSUE THREAD

**Issue by corneliusroemer** [loculus-project/loculus#1820] opened 2024-05-08 14:54 UTC
This is our most common E2E failure right now, it's stochastic and weird. Could be related to kubernetes being not designed to run in a Github action in terms of the amount of RAM/CPU available.

```
Error: page.goto: Connection terminated unexpectedly
    Call log:
      - navigating to "http://localhost:3000/seq/LOC_00000MR.2", waiting until "load"


       at pages/sequences/sequences.page.ts:27

      25 |
      26 |     public async goto(accessionVersion: AccessionVersion) {
    > 27 |         await this.page.goto(`${baseUrl}${routes.sequencesDetailsPage(accessionVersion)}`);
         |                         ^
      28 |         await expect(this.page).toHaveTitle(getAccessionVersionString(accessionVersion));
      29 |     }
      30 |

        at SequencePage.goto (/home/runner/work/loculus/loculus/website/tests/pages/sequences/sequences.page.ts:27:25)
        at /home/runner/work/loculus/loculus/website/tests/pages/sequences/accession.spec.ts:41:28
```

**Comment by theosanderson** [comment] 2024-09-02 19:57
I'm closing this as I don't think we see many E2E errors these days and I guess it was maybe the cause I pointed to above. Feel free to reopen

**Closed by theosanderson** 2024-09-02 19:57 UTC
Labels: bug, e2e

**Comment by corneliusroemer** [comment] 2024-09-02 20:23
Yeah I think I fixed this in one of my test PRs
